-- MySQL Script generated by MySQL Workbench
-- Fri Nov  4 14:07:04 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imoveis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imoveis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imoveis` DEFAULT CHARACTER SET utf8 ;
USE `imoveis` ;

-- -----------------------------------------------------
-- Table `imoveis`.`imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imoveis`.`imovel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `endereco` VARCHAR(180) NOT NULL,
  `descricao` VARCHAR(250) NOT NULL,
  `valorVenda` DECIMAL NULL,
  `valorLocacao` DECIMAL NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imoveis`.`proprietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imoveis`.`proprietario` (
  `id` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(120) NOT NULL,
  `email` VARCHAR(120) NOT NULL,
  `cpf` VARCHAR(14) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `imoveis`.`arquivos_imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imoveis`.`arquivos_imovel` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_imovel` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `nomeArquivo` VARCHAR(120) NOT NULL,
  `formatoArquivo` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `imoveis`.`imovel`
-- -----------------------------------------------------
START TRANSACTION;
USE `imoveis`;
INSERT INTO `imoveis`.`imovel` (`id`, `endereco`, `descricao`, `valorVenda`, `valorLocacao`) VALUES (1, 'Vila Belmiro, Santos - SP', 'Casa de 3 quartos na vila Belmiro em Santos', 895000.00, NULL);
INSERT INTO `imoveis`.`imovel` (`id`, `endereco`, `descricao`, `valorVenda`, `valorLocacao`) VALUES (2, 'Ponta da Praia, Santos - SP', 'Apartamento à venda no bairro Ponta da Praia', 715000.00, NULL);
INSERT INTO `imoveis`.`imovel` (`id`, `endereco`, `descricao`, `valorVenda`, `valorLocacao`) VALUES (3, 'Gonzaga, Santos - SP', 'Apartamento Duplex à venda no bairro Gonzaga', 1280000.00, NULL);
INSERT INTO `imoveis`.`imovel` (`id`, `endereco`, `descricao`, `valorVenda`, `valorLocacao`) VALUES (4, 'Embaré, Santos - SP', 'Apartamento à venda no bairro Embaré', 299999.99, NULL);
INSERT INTO `imoveis`.`imovel` (`id`, `endereco`, `descricao`, `valorVenda`, `valorLocacao`) VALUES (5, 'Aparecida, Santos - SP', 'Casa Normal à venda no bairro Aparecida', 590000.00, NULL);

COMMIT;

